import { HomeWorld } from './home-world';

export const HOMEWORLDS: HomeWorld[] = [
  { weight: 1, description: "Your home world is a terrestrial planet overrun with dangerous creatures, such as giant animals, enraged elementals, swarms of voracious vermin, tormented undead, or massive colossi." },
  { weight: 5, description: "Your home world is a gas or ice giant containing a portal to another plane. You might live in the upper atmosphere, sail the world's dense gas seas, or hail from one of the planet's several moons." },
  { weight: 9, description: "Your home world is a verdant place where flora and fauna live with little interference and could even grow to immense sizes. It might be unexplored and dangerous, or a peaceful nature preserve." },
  { weight: 13, description: "Your home world is a tourist destination where life revolves around keeping patrons entertained. It might be visited for its ruins, casinos, theme parks, or idyllic scenery." },
  { weight: 17, description: "Your home world is the site of a miraculous decennial phenomenon. Perhaps its orbit crosses through the atmosphere of another planet, or it teleports throughout the universe to orbit different suns." },
  { weight: 21, description: "Your home world is at war on a national, planetary, or interstellar scale. Many citizens are soldiers, and those that aren't support the war effort in their own way. You've likely lost loved ones to battle." },
  { weight: 25, description: "Your home world is overrun by hostile forces. Whatever their treatment of your people, you might embrace the new regime, rebel against it, remain indifferent, or strive to go unnoticed." },
  { weight: 29, description: "Your home world is a post-apocalyptic wasteland, destroyed perhaps by meteor impacts, war, or pollution. The survivors might live hidden in subterranean bunkers or scrounge through the wreckage of the past in the barren wastelands." },
  { weight: 33, description: "Your home world is inhospitable to organic life. It might have extreme temperatures, a toxic atmosphere, or fatal radiation levels. Surviving here required specialized tools, such as magic, equipment, or even divine intercession." },
  { weight: 37, description: "Your home world is a massive living creature, host to an entire biosphere. If your society is aware of its nature, they might treat the creature like a pet, a subordinate, or a god." },
  { weight: 41, description: "Your home world is harried by extreme environmental forces, such as hurricanes, thunderstorms, or volcanic eruptions. These disasters could be natural, magical, technological, extraplanar, or signs of a god's displeasure." },
  { weight: 45, description: "Your home world is a large, urban settlement. Whatever its size or location, you live amid bustling crowds and the hectic buzz of city life." },
  { weight: 49, description: "You're from a newly-founded colony. Your community is tight-knit, and the world outside is largely unexplored. Whether life is serene or dangerous, thriving or failing, the colony and its residents are focused mainly on survival." },
  { weight: 53, description: "You're from a physically-confined community whose citizens have never crossed its borders. You might have lived in a cave system, fallout shelter, walled-in community, or mobile fortress. You might feel safe within these confines or yearn to break free." },
  { weight: 57, description: "You're from a mobile community, such as a nomadic colony, a traveling circus troop, a flotilla adrift on a flooded world, or a small fleet of starships traversing the galaxy together." },
  { weight: 61, description: "You grew up in an educational institute or specialized training program. It might have been localized, such as in a monastery, school, or military base, or it might have been in a vast university-city." },
  { weight: 65, description: "You're from a city that flies through the skies of its home planet. Your people might have hated the world below, ignored it, fled from it, or considered themselves its protectors." },
  { weight: 69, description: "Your home is a starship, and its crew like family. They might have been long-haul truckers, mercenaries, smugglers, space pirates, surveyors, or musicians touring the galaxy." },
  { weight: 73, description: "You come from a colony ship designed to relocate large populations to new planets. The colonists might be daring explorers, political exiles, religious pilgrims, or refugees fleeing from a destroyed world." },
  { weight: 77, description: "You live on a space station. It might have been a large urban metropolis, a corporate-owned way station, or a scientific research facility." },
  { weight: 81, description: "You're from a community of miners. They might have been nomadic, moving from prospect to prospect, or they might have stayed working one promising vein for months or years." },
  { weight: 85, description: "You hail from a society that was built upon the ruins of another culture. Most citizens might pay these ruins little mind, though some consider them holy sites, subjects of study, or places to explore for a thrill." },
  { weight: 89, description: "Your society comprises a utopia built and maintained by the labor of hidden slums; you might come from either side of this social divide, fallen or climbed from one to the other, or be unaware of the division." },
  { weight: 93, description: "You were found adrift in an escape pod with no memory of how you got there or where you're from." },
  { weight: 96, description: "You're from another plane of existence, such as the transitory Drift, the riotous First World of the fey, or the shimmering slopes of Heaven." },
  { weight: 99, description: "You come from a simulation under constant observation, unaware your world was artificial. Life might have been a dangerous fight for survival, a blissful utopia, or anything in-between. The simulation's architects and their objectives might be shrouded in mystery." },
]
