import { MajorEvent } from "./major-event";

export const MAJOREVENTS: MajorEvent[] = [
  { weight: 1, description: "You don't know who you are or where you came from. Your missing memories might be a result of amnesia, repression, or a memory-modification procedure. You're driven to uncover your past." },
  { weight: 3, description: "You were once an animal, but somehow you gained sapience, whether through the power of technology, magic, or divine will. You've adapted to society well but retain some animalistic behaviors." },
  { weight: 5, description: "You distinguished yourself as extraordinary, perhaps through academic excellence, a gladiatorial competition, or an important discovery. You might embrace, hate, or struggle with your reputation." },
  { weight: 10, description: "You made an important scientific or anthropological discovery and strive to make more. You yearn to push the boundaries of knowledge, perhaps exploring the galaxy to uncover mysteries or unearth relics of the past." },
  { weight: 15, description: "You crash-landed on an alien world, becoming stranded for hours, days, or decades. You likely struggled for survival and might have fought fierce beasts, traversed treacherous landscapes, or made contact with an alien species." },
  { weight: 19, description: "You were cursed. You might have bad luck, strange features, or an unfortunate tendency to self-sabotage in embarrassing ways. You're searching for a cure and might turn to faith, magic, or superstition to find it." },
  { weight: 23, description: "You fell into debt, and payment is past due. You might have gone to extreme lengths to repay loaners, such as theft, gambling, IOUs, or indentured servitude." },
  { weight: 27, description: "You won the lottery, were the beneficiary of an inheritance, or otherwise obtained something of great value. Your good fortune might have been met with celebration, jealousy, false friendship, or theft." },
  { weight: 31, description: "You came into possession of something you shouldn't have, perhaps a magical relic, a cutting-edge prototype, or classified information; whatever it is, its owners are determined to retrieve it-and they might not be the only ones." },
  { weight: 35, description: "You obtained a mysterious key, coordinates, or a map you suspect leads to something valuable-perhaps a place, object, or wealth. Whatever the prize, you're not the only one searching for it." },
  { weight: 39, description: "You've been repeatedly mistaken for someone else thanks to a strong resemblance, or they're often mistaken for you. You might have access to their wealth, gain their enemies, or be the victim of identity theft." },
  { weight: 43, description: "You accidentally wronged someone and are struggling to live with (or escape) the consequences. Your negligence might have caused property damage, injury, or death. Those you wronged might be innocent victims, powerful public figures, or criminals seeking revenge." },
  { weight: 47, description: "You spent time with someone who inspired you to follow in their footsteps, such as a crime lord, doctor, musician, or war hero. You idolize them, whether they deserve it or not." },
  { weight: 51, description: "You met a rare creature and were changed by the encounter. It might have been a demon, a mi-go, or a unicorn. You might live in fear of the creature or yearn to meet it again." },
  { weight: 55, description: "You fell under the influence of a criminal, and as a result you took the fall for a crime-whether you really did it or not. You might have served jail time, been exiled, or fled; you still might have a bounty on your head." },
  { weight: 59, description: "Someone you trusted betrayed you. They might have been an individual, such as a lover, sibling, or friend-or perhaps a group, such as law enforcement, religious leaders, or employers." },
  { weight: 63, description: "You seek revenge against someone who wronged you. They might have slandered you, robbed you, hurt your family, or killed your pet. Whatever they did, you're furious, and believe whatever repercussions they faced were inadequate." },
  { weight: 67, description: "You were the subject of experimentation. You might have been abducted or tricked into it, or maybe you volunteered. Either way, it was probably painful, and you might still suffer side effects. If you're an escapee, the experimenters might be looking for you." },
  { weight: 71, description: "You took a dangerous stand for your oppressed or endangered people. You might be an activist, freedom fighter, or revolutionary. You might uphold your morals or be willing to break them to achieve your goals." },
  { weight: 75, description: "Someone close to you went missing. They might have gotten lost or been taken, or they might have disappeared of their own volition, the reasons for which seem embroiled in mystery. Finding them is important to you." },
  { weight: 79, description: "Someone close to you died, such as a friend, mentor, or parent, perhaps leaving you alone in life. You might have difficulty accepting their death, be driven to investigate it, or want revenge for it." },
  { weight: 83, description: "Disaster, such as extreme weather or war, destroyed your home, likely hurting or even killing people you care about. You're homeless and struggling to find your place in the galaxy. You might care for other survivors, such as an orphaned child or lost pet." },
  { weight: 87, description: "You were shunted here from the past, future, or an alternate dimension. You might encounter familiar faces, perhaps even another you, but they're not the people you know. You're likely motivated to find a way home." },
  { weight: 91, description: "You have prophetic dreams or visions of another dimension, or you hear voices no one else perceives. The purpose, source, and veracity of these strange occurrences are unknown to you." },
  { weight: 95, description: "You died or came close. You might be alive, undead, or possessing a robot or plant. You might have seen strange visions or felt the weight of your sins. Whatever your experience, death changed you." }
]
