import { PartyRelationship } from "./party-relationship";

export const PARTYRELATIONSHIPS: PartyRelationship[] = [
  { weight: 1, description: "You and this character are family. You might be joined by blood, marriage, adoption, oaths, or through long-standing bonds of friendship so close as to make you effectively kin." },
  { weight: 5, description: "You and this character shared an intimate relationship, which might still be ongoing. You might have been lovers, soul mates, or considered yourselves two halves of a single identity. You know each other inside and out and have many shared acquaintances." },
  { weight: 9, description: "You and this character were once close, though circumstance, distance, or time caused you to drift apart. You might be happy to see each other, interact awkwardly and have nothing in common, bicker over past slights, or even utterly despise each other." },
  { weight: 13, description: "You and this character met online, have been friends for years, and are meeting in person for the first time. You have shared interests and jokes; you might or might not get along in person as well as you hoped." },
  { weight: 17, description: "You and this character used to be enemies, but over time you became friends. You're brutally honest with each other, and you might regularly mock or tease each other or bring up past conflicts. However, when push comes to shove, you've got each other's backs." },
  { weight: 21, description: "You and this character are competitive rivals striving to outdo one another. Whether your rivalry is friendly or cutthroat, you push each other to try harder, aim higher, achieve greater feats, and reach your full potential." },
  { weight: 25, description: "You and this character served together in a military unit. You celebrated, fought, struggled, and suffered through loss together. You might be the sole survivors of your unit. Love them or hate them, you trust them to fight alongside you." },
  { weight: 29, description: "You and this character are colleagues who worked together in the past or present. You know each other's habits and probably work well together, even if you don't get along personally." },
  { weight: 33, description: "You and this character share a professional relationship, such as boss and employee, teacher and student, or superior and subordinate. You probably want to make a good impression on each other and might be uncomfortable socializing." },
  { weight: 37, description: "You and this character collaborated together on a project. You might have been co-stars in a theatre troupe or holovid program, members of the same band or orchestra, scientific research partners, or construction workers on the same build site." },
  { weight: 41, description: "You and this character trained together. You might have enrolled in the same classes at school or university, gone through military training together, or been on the same sports team." },
  { weight: 45, description: "You're a fan of this character's accomplishments and work, or they are of yours. One of you might even be a customer or patron of the other. Both of you likely appreciate each other and can count on the other's support." },
  { weight: 49, description: "You and this character are criminal associates. You understand— but might not trust—each other. Your illicit activities might be known to other members of the party, or not." },
  { weight: 53, description: "You and this character are friends of the same person. You met through a mutual acquaintance or have overlapping social circles, and though you've socialized, you aren't close." },
  { weight: 57, description: "You and this character were both hurt, tricked, or ripped off by the same person. You might bond over shared misfortune, fear, or desire for vengeance." },
  { weight: 61, description: "You and this character temporarily competed, such as by applying for the same job or pursuing the same lover, but you were both passed over for someone else and now bond over shared rejection." },
  { weight: 65, description: "You and this character know each other by reputation but have never met. You might look forward to working together, regard each other with mild interest, or dread every interaction." },
  { weight: 69, description: "You and this character were both arrested and falsely accused of the same crime. You might have proven your innocence together, served time in the same prison, or been pardoned but live with a tarnished reputation. You might both hold a grudge against those who accused or condemned you." },
  { weight: 73, description: "You and this character are from the same neighborhood, settlement, country, or planet. You might be neighbors or strangers bonding over shared roots and connections. They might remind you of home, so you might find their presence comforting." },
  { weight: 77, description: "You and this character have mutual interest in a hobby that you regularly engage in together. You might go clubbing, hunting, perform music, or meet regularly to play a favorite game." },
  { weight: 81, description: "You and this character share an intense passion for a specific hobby or media. You might love the same band, game, movie, or sport; both of you might even belong to the same fan club.. You discuss your shared interest for hours, in greater depth than anyone else thinks it deserves." },
  { weight: 85, description: "You and this character are affiliated with the same organization, such as AbadarCorp, the Free Captains, the Golden League, the Starfinder Society, the Xenowardens, or a local charity. If it's a large organization, it's unlikely you know each other personally." },
  { weight: 89, description: "You and this character are members of the same philosophy, religion, or cult; you might even be members of the same congregation. Although you might quibble over minor philosophical matters, you support each other in matters of faith and morality." },
  { weight: 93, description: "You and this character met while sharing an enjoyable experience together. You might have been volunteers at the same charity, spectators at a sporting event, or passengers on the same planetary cruise." },
  { weight: 97, description: "You and this character survived the same mass tragedy, perhaps an invasion, crash landing, or hurricane. Whether or not you met during the disaster, you've bonded over your shared loss and suffering in the time since." }
]