import { NpcQuirk } from './npc-quirk';

export const NPCQUIRKS: NpcQuirk[] = [
    { weight: 1, description: "Always wears a bright top hat embroidered with a kaukariki" },
    { weight: 2, description: "Always snacking on various flavored honeys" },
    { weight: 3, description: "Absentmindedly hums the latest synth-pop hits" },
    { weight: 4, description: "Mortally terrified of squoxes thanks to a childhood mishap" },
    { weight: 5, description: "An aspiring chef who searches the galaxy for new ingredients" },
    { weight: 6, description: "Spends their free time playing infosphere strategy games" },
    { weight: 7, description: "Always well-apprised of the latest celebrity gossip" },
    { weight: 8, description: "Has a secret and unrequited crush on an acquaintance" },
    { weight: 9, description: "Extremely sensitive to heat and always carries a portable fan" },
    { weight: 10, description: "Intentionally talks louder than everyone else" },
    { weight: 11, description: "Quick-tempered, but quick to apologize for their outbursts" },
    { weight: 12, description: "Looks for any opportunity to share a limitless supply of factoids" },
    { weight: 13, description: "Speaks very slowly, with long pauses between most words" },
    { weight: 14, description: "Follows the latest fashions, replacing their wardrobe regularly" },
    { weight: 15, description: "Insists on interpreting others’ dreams for deep meaning" },
    { weight: 16, description: "Enjoys acting extremely mysterious, even among friends" },
    { weight: 17, description: "Normally rather grouchy, but has a soft spot for animals" },
    { weight: 18, description: "Takes their duties, even minor ones, extremely seriously" },
    { weight: 19, description: "Makes friends very easily but never remembers their names" },
    { weight: 20, description: "Always tired, no matter how much rest they’ve gotten" },
    { weight: 21, description: "Has an encyclopedic knowledge of the local laws" },
    { weight: 22, description: "Loves playing vidgames but is not particularly good at them" },
    { weight: 23, description: "Has an acute sense of smell and often comments on odors" },
    { weight: 24, description: "Names all of their weapons or equipment after historical figures" },
    { weight: 25, description: "Never misses a chance to relate a childhood anecdote" },
    { weight: 26, description: "Has always wanted to be a dashing adventurer-pilot" },
    { weight: 27, description: "Never forgives an insult against them, no matter how minor" },
    { weight: 28, description: "Constantly talks about their large collection of niche antiques" },
    { weight: 29, description: "Loves poetry and always carries a notebook to jot down ideas" },
    { weight: 30, description: "Takes credit for others’ successes" },
    { weight: 31, description: "Loves to travel and has visited numerous worlds" },
    { weight: 32, description: "Tends to get distracted mid-conversation and changes the subject" },
    { weight: 33, description: "Paints amateurish portraits and always looks for new subjects" },
    { weight: 34, description: "Has multiple identities and sometimes forgets to respond to names they’ve given" },
    { weight: 35, description: "Is deeply impressed by magic and spellcasters" },
    { weight: 36, description: "Has a penchant for challenging people to duels" },
    { weight: 37, description: "Thinks highly of themself and is unintentionally condescending" },
    { weight: 38, description: "Enjoys knitting handicrafts and pushing them on others" },
    { weight: 39, description: "Gets so focused on tasks that they forget to blink or move" },
    { weight: 40, description: "Is a devout follower of their deity, but interprets their tenets in an unusual way" },
    { weight: 41, description: "Dotes on a pet incessantly and narrates its thoughts in falsetto" },
    { weight: 42, description: "Hates their day job and daydreams about becoming a vid star" },
    { weight: 43, description: "Is extremely risk-averse except in defense of their loved ones" },
    { weight: 44, description: "Takes great pride in their family lineage" },
    { weight: 45, description: "Extremely clumsy, always knocking something over or breaking things" },
    { weight: 46, description: "Gullible enough to have accidentally joined not one, but two cults" },
    { weight: 47, description: "Always reading mystery novels and fancies themself an amateur detective" },
    { weight: 48, description: "Has a new hobby every other week" },
    { weight: 49, description: "Not shy about voicing their extraordinarily vehement brand preferences" },
    { weight: 50, description: "Is entrenched in a pyramid scheme and enthusiastically offers opportunities to join" },
    { weight: 51, description: "Attempts to place wagers on every possible event, no matter how mundane" },
    { weight: 52, description: "Obsessed with conspiracy theories, the wilder the better" },
    { weight: 53, description: "Peppers their conversations with terrible puns" },
    { weight: 54, description: "Is an amateur linguist who wants to learn as many languages as possible" },
    { weight: 55, description: "Can’t resist embellishing tales of their exploits" },
    { weight: 56, description: "Can’t be intimidated, but tears up at any display of empathy" },
    { weight: 57, description: "Proudly displays several commissioned statuettes of themself" },
    { weight: 58, description: "Won’t go anywhere without their lucky hip flask" },
    { weight: 59, description: "Mixes metaphors and uses mashed-up aphorisms" },
    { weight: 60, description: "Challenges new acquaintances to a game of Imperial Conquest" },
    { weight: 61, description: "Extremely learned in their field of study but absent-minded" },
    { weight: 62, description: "Makes dramatic speeches about mundane events" },
    { weight: 63, description: "Always has headphones on, blaring custom playlists" },
    { weight: 64, description: "Is meticulous and pays close attention to minor aesthetic details" },
    { weight: 65, description: "Is extremely interested in dragons" },
    { weight: 66, description: "Is often underestimated because of their bubbly demeanor" },
    { weight: 67, description: "Judges others by what they have and haven’t read" },
    { weight: 68, description: "Prefers technological solutions and is wary of magic" },
    { weight: 69, description: "Tinkers with virtual intelligence projects in their free time" },
    { weight: 70, description: "Moves around constantly, never staying in the same spot" },
    { weight: 71, description: "Lies about being able to play a musical instrument" },
    { weight: 72, description: "Has a photographic memory but doesn’t realize it’s unusual" },
    { weight: 73, description: "Keeps numerous pets of a wide variety of species" },
    { weight: 74, description: "Always experiments with the latest pyrotechnics" },
    { weight: 75, description: "Collects decks of playing cards from throughout the galaxy" },
    { weight: 76, description: "Very contrarian and loves to argue even when they agree" },
    { weight: 77, description: "Quotes philosophers in everyday conversation" },
    { weight: 78, description: "Always sees the best in people, even to their own detriment" },
    { weight: 79, description: "Very quiet until someone gets them talking about a pet subject" },
    { weight: 80, description: "Utterly disinterested in everyone and everything" },
    { weight: 81, description: "Makes up a nickname for everyone they meet" },
    { weight: 82, description: "Prefers analog equipment to technological, for the aesthetic" },
    { weight: 83, description: "Has an uncanny sense for when someone has a secret" },
    { weight: 84, description: "Wants to be someone’s mentor but hasn’t found any mentees" },
    { weight: 85, description: "Easily starstruck by even minor celebrities" },
    { weight: 86, description: "Breaks into songs from their favorite musicals whenever remotely relevant" },
    { weight: 87, description: "Fond of expensive jewelry, and prefers sapphires" },
    { weight: 88, description: "A gifted but incredibly shy performer who refuses the limelight" },
    { weight: 89, description: "Loves to barter and relentlessly offers trades that heavily favor them" },
    { weight: 90, description: "Always very well-dressed, even at informal occasions" },
    { weight: 91, description: "Thinks they know best and always volunteers to give others unsolicited advice" },
    { weight: 92, description: "Enjoys matchmaking, whether romantic or platonic" },
    { weight: 93, description: "Encourages everyone they meet to monetize even the most minor talents" },
    { weight: 94, description: "Jumps to conclusions and (incorrectly) finishes others’ sentences" },
    { weight: 95, description: "Constantly asks conversation partners to repeat themselves" },
    { weight: 96, description: "Tries to imitate stunts from their favorite action vids" },
    { weight: 97, description: "Has a deep nostalgic streak even about recent events" },
    { weight: 98, description: "Bends over backward to avoid admitting when they’re wrong" },
    { weight: 99, description: "Attempts to live well beyond their limited means" },
    { weight: 100, description: "Laughs uncontrollably when stressed" }
]
